<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pharmacy Bill - <?php echo e($bill->bill_number); ?></title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #750096;
            font-size: 24px;
        }
        .header h2 {
            margin: 5px 0;
            color: #666;
            font-size: 18px;
        }
        .bill-info {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
        }
        .bill-info div {
            width: 48%;
        }
        .bill-info h3 {
            margin: 0 0 10px 0;
            color: #750096;
            font-size: 14px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
        }
        .bill-info table {
            width: 100%;
        }
        .bill-info td {
            padding: 2px 0;
        }
        .bill-info th {
            text-align: left;
            width: 40%;
            font-weight: bold;
        }
        .medicine-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .medicine-table th,
        .medicine-table td {
            border: 1px solid #333;
            padding: 8px;
            text-align: left;
        }
        .medicine-table th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .medicine-table .text-right {
            text-align: right;
        }
        .summary-table {
            width: 100%;
            border-collapse: collapse;
            margin-left: auto;
            margin-right: 0;
            max-width: 300px;
        }
        .summary-table th,
        .summary-table td {
            border: 1px solid #333;
            padding: 8px;
            text-align: left;
        }
        .summary-table th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .summary-table .text-right {
            text-align: right;
        }
        .total-row {
            background-color: #e9ecef;
            font-weight: bold;
        }
        .notes {
            margin-top: 20px;
            padding: 10px;
            background-color: #f8f9fa;
            border-left: 4px solid #750096;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            border-top: 1px solid #ddd;
            padding-top: 20px;
            color: #666;
        }
        @media print {
            body { margin: 0; }
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>HOSPITAL MANAGEMENT SYSTEM</h1>
        <h2>PHARMACY BILL</h2>
    </div>

    <div class="bill-info">
        <div>
            <h3>Bill Information</h3>
            <table>
                <tr>
                    <th>Bill Number:</th>
                    <td><?php echo e($bill->bill_number); ?></td>
                </tr>
                <tr>
                    <th>Date:</th>
                    <td><?php echo e($bill->date ? $bill->date->format('d/m/Y h:i A') : '-'); ?></td>
                </tr>
                <tr>
                    <th>Case Reference ID:</th>
                    <td><?php echo e($bill->case_reference_id ?? '-'); ?></td>
                </tr>
                <tr>
                    <th>Generated By:</th>
                    <td><?php echo e($bill->generatedBy->name ?? '-'); ?></td>
                </tr>
            </table>
        </div>
        <div>
            <h3>Patient Information</h3>
            <table>
                <tr>
                    <th>Patient Name:</th>
                    <td>
                        <?php if($bill->patient): ?>
                            <?php echo e($bill->patient->patient_name); ?> (ID: <?php echo e($bill->patient->id); ?>)
                        <?php else: ?>
                            <?php echo e($bill->customer_name ?? '-'); ?>

                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <th>Customer Type:</th>
                    <td><?php echo e($bill->customer_type ?? '-'); ?></td>
                </tr>
                <tr>
                    <th>Doctor Name:</th>
                    <td><?php echo e($bill->doctor_name ?? '-'); ?></td>
                </tr>
                <?php if($bill->patient): ?>
                <tr>
                    <th>Contact:</th>
                    <td><?php echo e($bill->patient->mobileno ?? '-'); ?></td>
                </tr>
                <?php endif; ?>
            </table>
        </div>
    </div>

    <h3>Medicine Details</h3>
    <table class="medicine-table">
        <thead>
            <tr>
                <th>Medicine Name</th>
                <th>Batch No</th>
                <th>Expiry Date</th>
                <th class="text-right">Quantity</th>
                <th class="text-right">Sale Price (INR)</th>
                <th class="text-right">Amount (INR)</th>
            </tr>
        </thead>
        <tbody>
            <?php $__empty_1 = true; $__currentLoopData = $bill->billDetails; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $detail): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
            <tr>
                <td>
                    <div>
                        <div><strong><?php echo e($detail->medicineBatch->pharmacy->medicine_name ?? '-'); ?></strong></div>
                        <?php if($detail->medicineBatch->pharmacy->company): ?>
                        <div style="font-size: 10px; color: #666;"><?php echo e($detail->medicineBatch->pharmacy->company->company_name); ?></div>
                        <?php endif; ?>
                    </div>
                </td>
                <td><?php echo e($detail->medicineBatch->batch_no ?? '-'); ?></td>
                <td><?php echo e($detail->medicineBatch->expiry ? $detail->medicineBatch->expiry->format('d/m/Y') : '-'); ?></td>
                <td class="text-right"><?php echo e($detail->quantity); ?></td>
                <td class="text-right"><?php echo e(number_format($detail->sale_price, 2)); ?></td>
                <td class="text-right"><strong><?php echo e(number_format($detail->amount, 2)); ?></strong></td>
            </tr>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
            <tr>
                <td colspan="6" class="text-center">No medicine details found</td>
            </tr>
            <?php endif; ?>
        </tbody>
    </table>

    <div style="display: flex; justify-content: space-between; align-items: flex-start;">
        <div style="width: 48%;">
            <?php if($bill->note): ?>
            <div class="notes">
                <h4 style="margin: 0 0 10px 0; color: #750096;">Notes</h4>
                <p style="margin: 0;"><?php echo e($bill->note); ?></p>
            </div>
            <?php endif; ?>
        </div>
        <div style="width: 48%;">
            <h3>Bill Summary</h3>
            <table class="summary-table">
                <tr>
                    <th>Total (INR)</th>
                    <td class="text-right"><?php echo e(number_format($bill->total, 2)); ?></td>
                </tr>
                <tr>
                    <th>Discount (INR)</th>
                    <td class="text-right"><?php echo e(number_format($bill->discount, 2)); ?> (<?php echo e(number_format($bill->discount_percentage, 2)); ?>%)</td>
                </tr>
                <tr>
                    <th>Tax (INR)</th>
                    <td class="text-right"><?php echo e(number_format($bill->tax, 2)); ?></td>
                </tr>
                <tr class="total-row">
                    <th>Net Amount (INR)</th>
                    <td class="text-right" style="font-size: 14px;"><?php echo e(number_format($bill->net_amount, 2)); ?></td>
                </tr>
            </table>
        </div>
    </div>

    <div class="footer">
        <p>Thank you for your business!</p>
        <p>Generated on <?php echo e(now()->format('d/m/Y h:i A')); ?></p>
    </div>

    <div class="no-print" style="margin-top: 20px; text-align: center;">
        <button onclick="window.print()" class="btn btn-primary">Print Bill</button>
        <button onclick="window.close()" class="btn btn-secondary">Close</button>
    </div>
</body>
</html>
<?php /**PATH C:\xampp\htdocs\hims\resources\views\admin\pharmacy\billing\print.blade.php ENDPATH**/ ?>