<?php $__env->startSection('content'); ?>
<div class="row justify-content-center">
    <div class="col-md-11">
        <div class="card shadow-sm border-0 mt-4">
            <div class="card-header" style="background: linear-gradient(-90deg, #75009673 0%, #CB6CE673 100%)">
                <div class="d-flex justify-content-between align-items-center">
                    <h5 class="mb-0" style="color: #750096">
                        <i class="fas fa-file-invoice me-2"></i>Pharmacy Bill Details
                    </h5>
                    <div class="btn-group">
                        <a href="<?php echo e(route('pharmacy.billing.edit', $bill->id)); ?>" class="btn btn-warning btn-sm">
                            <i class="ti ti-edit me-1"></i>Edit
                        </a>
                        <a href="<?php echo e(route('pharmacy.billing.print', $bill->id)); ?>" class="btn btn-info btn-sm" target="_blank">
                            <i class="ti ti-printer me-1"></i>Print
                        </a>
                        <a href="<?php echo e(route('pharmacy.billing.index')); ?>" class="btn btn-secondary btn-sm">
                            <i class="ti ti-arrow-left me-1"></i>Back
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <!-- Bill Header Information -->
                <div class="row mb-4">
                    <div class="col-md-6">
                        <h6 class="text-primary mb-3">Bill Information</h6>
                        <table class="table table-borderless">
                            <tr>
                                <th width="40%">Bill Number:</th>
                                <td><span class="fw-semibold text-primary"><?php echo e($bill->bill_number); ?></span></td>
                            </tr>
                            <tr>
                                <th>Date:</th>
                                <td><?php echo e($bill->date ? $bill->date->format('d/m/Y h:i A') : '-'); ?></td>
                            </tr>
                            <tr>
                                <th>Case Reference ID:</th>
                                <td><?php echo e($bill->case_reference_id ?? '-'); ?></td>
                            </tr>
                            <tr>
                                <th>Generated By:</th>
                                <td><?php echo e($bill->generatedBy->name ?? '-'); ?></td>
                            </tr>
                        </table>
                    </div>
                    <div class="col-md-6">
                        <h6 class="text-primary mb-3">Patient Information</h6>
                        <table class="table table-borderless">
                            <tr>
                                <th width="40%">Patient Name:</th>
                                <td>
                                    <?php if($bill->patient): ?>
                                        <?php echo e($bill->patient->patient_name); ?> (ID: <?php echo e($bill->patient->id); ?>)
                                    <?php else: ?>
                                        <?php echo e($bill->customer_name ?? '-'); ?>

                                    <?php endif; ?>
                                </td>
                            </tr>
                            <tr>
                                <th>Customer Type:</th>
                                <td><?php echo e($bill->customer_type ?? '-'); ?></td>
                            </tr>
                            <tr>
                                <th>Doctor Name:</th>
                                <td><?php echo e($bill->doctor_name ?? '-'); ?></td>
                            </tr>
                            <?php if($bill->patient): ?>
                            <tr>
                                <th>Contact:</th>
                                <td><?php echo e($bill->patient->mobileno ?? '-'); ?></td>
                            </tr>
                            <?php endif; ?>
                        </table>
                    </div>
                </div>

                <!-- Medicine Details -->
                <div class="row mb-4">
                    <div class="col-12">
                        <h6 class="text-primary mb-3">Medicine Details</h6>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead class="table-light">
                                    <tr>
                                        <th>Medicine Name</th>
                                        <th>Batch No</th>
                                        <th>Expiry Date</th>
                                        <th class="text-end">Quantity</th>
                                        <th class="text-end">Sale Price (INR)</th>
                                        <th class="text-end">Amount (INR)</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $__empty_1 = true; $__currentLoopData = $bill->billDetails; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $detail): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                                    <tr>
                                        <td>
                                            <div>
                                                <div class="fw-semibold"><?php echo e($detail->medicineBatch->pharmacy->medicine_name ?? '-'); ?></div>
                                                <?php if($detail->medicineBatch->pharmacy->company): ?>
                                                <small class="text-muted"><?php echo e($detail->medicineBatch->pharmacy->company->company_name); ?></small>
                                                <?php endif; ?>
                                            </div>
                                        </td>
                                        <td><?php echo e($detail->medicineBatch->batch_no ?? '-'); ?></td>
                                        <td><?php echo e($detail->medicineBatch->expiry ? $detail->medicineBatch->expiry->format('d/m/Y') : '-'); ?></td>
                                        <td class="text-end"><?php echo e($detail->quantity); ?></td>
                                        <td class="text-end"><?php echo e(number_format($detail->sale_price, 2)); ?></td>
                                        <td class="text-end fw-semibold"><?php echo e(number_format($detail->amount, 2)); ?></td>
                                    </tr>
                                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                                    <tr>
                                        <td colspan="6" class="text-center text-muted">No medicine details found</td>
                                    </tr>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <!-- Bill Summary -->
                <div class="row">
                    <div class="col-md-6">
                        <?php if($bill->note): ?>
                        <h6 class="text-primary mb-3">Notes</h6>
                        <div class="card bg-light">
                            <div class="card-body">
                                <p class="mb-0"><?php echo e($bill->note); ?></p>
                            </div>
                        </div>
                        <?php endif; ?>
                    </div>
                    <div class="col-md-6">
                        <h6 class="text-primary mb-3">Bill Summary</h6>
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tr>
                                    <th width="40%">Total (INR)</th>
                                    <td class="text-end"><?php echo e(number_format($bill->total, 2)); ?></td>
                                </tr>
                                <tr>
                                    <th>Discount (INR)</th>
                                    <td class="text-end"><?php echo e(number_format($bill->discount, 2)); ?> (<?php echo e(number_format($bill->discount_percentage, 2)); ?>%)</td>
                                </tr>
                                <tr>
                                    <th>Tax (INR)</th>
                                    <td class="text-end"><?php echo e(number_format($bill->tax, 2)); ?></td>
                                </tr>
                                <tr class="table-primary">
                                    <th class="fw-bold">Net Amount (INR)</th>
                                    <td class="text-end fw-bold fs-5"><?php echo e(number_format($bill->net_amount, 2)); ?></td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.adminLayout', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\hims\resources\views\admin\pharmacy\billing\show.blade.php ENDPATH**/ ?>