<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Expense extends Model
{
    use HasFactory;

    protected $table = 'expenses';

    // Table does not include Laravel timestamps by default
    public $timestamps = false;

    protected $fillable = [
        'hospital_id',
        'branch_id',
        'exp_head_id',
        'name',
        'invoice_no',
        'date',
        'amount',
        'documents',
        'note',
        'is_active',
        'is_deleted',
        'generated_by',
    ];

    

    // Each expense belongs to an expense head
    public function expenseHead()
    {
        return $this->belongsTo(ExpenseHead::class, 'exp_head_id');
    }

    // Each expense may be generated by a user
    public function generatedBy()
    {
        return $this->belongsTo(User::class, 'generated_by');
    }
}
