<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OperationTheatre extends Model
{
    use HasFactory;

    protected $table = 'operation_theatre';

    protected $fillable = [
        'hospital_id',
        'branch_id',
        'opd_details_id',
        'ipd_details_id',
        'customer_type',
        'operation_id',
        'date',
        'operation_type',
        'consultant_doctor',
        'ass_consultant_1',
        'ass_consultant_2',
        'anesthetist',
        'anaethesia_type',
        'ot_technician',
        'ot_assistant',
        'result',
        'remark',
        'generated_by',
    ];

    /**
     * Relation with Operation
     */
    public function operation()
    {
        return $this->belongsTo(Operation::class, 'operation_id');
    }

    /**
     * Relation with Consultant Doctor (Staff)
     */
    public function consultant()
    {
        return $this->belongsTo(Staff::class, 'consultant_doctor');
    }

    /**
     * Relation with OPD Details
     */
    public function opdDetails()
    {
        return $this->belongsTo(OpdDetail::class, 'opd_details_id');
    }

    /**
     * Relation with IPD Details
     */
    public function ipdDetails()
    {
        return $this->belongsTo(IpdDetail::class, 'ipd_details_id');
    }

    /**
     * Relation with Generated By (User)
     */
    public function generatedBy()
    {
        return $this->belongsTo(User::class, 'generated_by');
    }
}
