<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PharmacyBillBasic extends Model
{
    use HasFactory;

    protected $table = 'pharmacy_bill_basic';

    protected $fillable = [
        'date',
        'patient_id',
        'ipd_prescription_basic_id',
        'case_reference_id',
        'customer_name',
        'customer_type',
        'doctor_name',
        'file',
        'total',
        'discount_percentage',
        'discount',
        'tax_percentage',
        'tax',
        'net_amount',
        'note',
        'generated_by',
    ];

    protected $casts = [
        'date' => 'datetime',
        'total' => 'decimal:2',
        'discount_percentage' => 'decimal:2',
        'discount' => 'decimal:2',
        'tax_percentage' => 'decimal:2',
        'tax' => 'decimal:2',
        'net_amount' => 'decimal:2',
    ];

    /**
     * Relationship: A pharmacy bill belongs to a patient
     */
    public function patient()
    {
        return $this->belongsTo(Patient::class, 'patient_id');
    }

    /**
     * Relationship: A pharmacy bill belongs to a case reference
     */
    public function caseReference()
    {
        return $this->belongsTo(CaseReference::class, 'case_reference_id');
    }

    /**
     * Relationship: A pharmacy bill belongs to a staff member (generated by)
     */
    public function generatedBy()
    {
        return $this->belongsTo(Staff::class, 'generated_by');
    }

    /**
     * Relationship: A pharmacy bill has many bill details
     */
    public function billDetails()
    {
        return $this->hasMany(PharmacyBillDetail::class, 'pharmacy_bill_basic_id');
    }

    /**
     * Relationship: A pharmacy bill belongs to an IPD prescription
     */
    public function ipdPrescription()
    {
        return $this->belongsTo(IpdPrescriptionBasic::class, 'ipd_prescription_basic_id');
    }

    /**
     * Get bill number with prefix
     */
    public function getBillNumberAttribute()
    {
        return 'PHAB' . str_pad($this->id, 2, '0', STR_PAD_LEFT);
    }

    /**
     * Scope: Filter by date range
     */
    public function scopeDateRange($query, $startDate, $endDate)
    {
        return $query->whereBetween('date', [$startDate, $endDate]);
    }

    /**
     * Scope: Filter by patient
     */
    public function scopeForPatient($query, $patientId)
    {
        return $query->where('patient_id', $patientId);
    }

    /**
     * Scope: Filter by doctor
     */
    public function scopeForDoctor($query, $doctorName)
    {
        return $query->where('doctor_name', 'like', '%' . $doctorName . '%');
    }
}